### ISSUE TITLE
节点数据同步不一致

### ISSUE THREAD

**Issue by bitwolaiye** [copernet/wormhole#1]
#### 现象

1. 我的节点前后发了两笔燃烧交易

https://www.blocktrail.com/tBCC/tx/d0f796bec4d457ecc3a971f57432ad713e1356f795d33237af575728374599ac
https://www.blocktrail.com/tBCC/tx/0b5ef02c4d96ac6b08cf436106c0f1b20ca5d601596701dce92336c6d9cda24a

仅有一笔在节点显示燃烧成功

2. 前后发行3种类型的token，只有第一笔交易token发送成功

同样在这个地址
https://www.blocktrail.com/tBCC/address/mpfYjVysvrhZWJXyW6b2ycNvCiMhL7zncD/transactions

3. 发行的token的列表不完整，与开发人员沟通后发现我的节点只显示少数几个token，不完整。

#### 解决

前后试了几种方式，有在开发人员帮助下定位到了应该是bitcoind的txindex参数默认未开启，导致查询历史交易会有问题（具体由开发人员来详细解释）。

如果已经是同步过的节点，需要

whc stop
wormholed -reindex -startclean=1 -txindex=1 -testnet -daemon

其中 -startclean=1 应该是会去清理虫洞的本地数据。该操作不清理本地已经同步的区块，也不会影响本地私钥。

**Comment by jjz** [comment]
Thanks!
