### ISSUE TITLE
Make Fail: build.h no such file or directory

### ISSUE THREAD

**Issue by bibodeng** [copernet/wormhole#2]
## Issue Description

I follow Steps to Make & Make install wormhole:

```
./autogen
./configure
make
make install
```

but in step `make` it fail:

```
build.h no such file or directory
```

## Screenshot

![image](https://user-images.githubusercontent.com/1180416/42979730-4ddcf234-8c06-11e8-89af-41d8d7f7dc0d.png)

What can I do to fix this problem?

**Comment by zymap** [comment]
you can fix it follow below steps:
```
cd share
./genbuild.sh ../src/obj/build.h
```
then make your project

**Comment by YG-FLUSH** [comment]
> you can fix it follow below steps:
> 
> ```
> cd share
> ./genbuild.sh ../src/obj/build.h
> ```
> 
> then make your project
No `genbuild.sh` file in the share directory
![image](https://user-images.githubusercontent.com/8018232/57609039-ada50100-75a0-11e9-854e-4c533b7b19d1.png)

**Comment by ludete** [comment]
Thanks, now if you want to build wormhole, you can follow the document : https://github.com/copernet/wormhole/blob/master/doc/build-in-docker.md.

This is a closed issue with the problem : https://github.com/copernet/wormhole/issues/2.

At 2019-05-13 17:01:44, "Yoge" <notifications@github.com> wrote:


you can fix it follow below steps:

cd share
./genbuild.sh ../src/obj/build.h


then make your project
No genbuild.sh file in the share directory
