### ISSUE TITLE
Error with selected inputs for the send transaction

### ISSUE THREAD

**Issue by telnetor** [copernet/wormhole#3]
whc已经生成了，但是转账和发行token都失败，这是为什么？
`
$ wormholed-cli whc_getbalance qpkm4gedmwjp675r7l5s47lul77xh4hwlumm96qgsv 1
{
  "balance": "10000000000",
  "reserved": "0"
}
$wormholed-cli whc_sendissuancefixed qpkm4gedmwjp675r7l5s47lul77xh4hwlumm96qgsv 1 1 0 "test" "test2" "sn-coin" "www.sn.coin" "my data" 2100000000000000000
error code: -206
error message:
Error with selected inputs for the send transaction

$ wormholed-cli whc_send "bchtest:qpkm4gedmwjp675r7l5s47lul77xh4hwlumm96qgsv" "bchtest:qq6hm9ma63jzfsa2nls5ua0ke3jdtrrf4yhz8xy6fj" 1 10
error code: -206
error message:
Error with selected inputs for the send transaction
`

**Comment by fengprofile** [comment]
这个地址bchtest:qpkm4gedmwjp675r7l5s47lul77xh4hwlumm96qgsv 没有BCH金额
