### ISSUE TITLE
 std::string strClassAB = "76a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac"; need modified

### ISSUE THREAD

**Issue by xiaomdong** [copernet/wormhole#4]
int mastercore::GetEncodingClass(const CTransaction& tx, int nBlock)
{
    bool hasExodus = false;
    bool hasMultisig = false;
    bool hasOpReturn = false;
    bool hasMoney = false;

    /* Fast Search
     * Perform a string comparison on hex for each scriptPubKey & look directly for Exodus hash160 bytes or omni marker bytes
     * This allows to drop non-Omni transactions with less work
     */
    std::string strClassC = "08776863";
    std::string strClassAB = "76a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac";

   76a914946cb2e08075bcbaf157e47bcb67eb2b2339d24288ac  need change to  the scriptPubKey of pubqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu08dsyxz98whc

**Comment by ludete** [comment]
当前WormHole 协议只是用C类交易，A，B两种交易不支持，随后会删除这些冗余代码。
