### ISSUE TITLE
创建Token的时候，直接报错：Error with selected inputs for the send transaction

### ISSUE THREAD

**Issue by snowpine** [copernet/wormhole#5]
按照教程：https://github.com/copernet/wormhole/blob/master/doc/WormHole%E6%B5%8B%E8%AF%95%E6%89%8B%E5%86%8C.docx

创建Token的时候，直接报错：Error with selected inputs for the send transaction，请问这是什么原因？
![image](https://user-images.githubusercontent.com/612599/43568328-e55065aa-9666-11e8-84ed-19db63f917f3.png)

系统：Ubuntu 16.04

**Comment by qshuai** [comment]
@snowpine Please check account balance of the specified address.
