### ISSUE TITLE
Building on mac returns error

### ISSUE THREAD

**Issue by pmitchev** [copernet/wormhole#9]
### Describe the issue

Building on macos (latest version) returns:

`CXX      omnicore/libwormholed_server_a-version.o`
`omnicore/version.cpp:9:14: fatal error: 'build.h' file not found`
`#    include "build.h"`
`             ^~~~~~~~~`
`1 error generated.`
`make[2]: *** [omnicore/libwormholed_server_a-version.o] Error 1`

#### If so, please list the steps to reproduce below:
./autogen.sh
./configure
make

### Expected behaviour
It should build successfully

### Actual behaviour
It does not build successfully.

I found this issue, but it seems the fix is already in the code:
https://github.com/OmniLayer/omnicore/issues/59

**Comment by pmitchev** [comment]
Same error on Ubuntu 18.04.1

**Comment by zymap** [comment]
You can try this way [https://github.com/copernet/wormhole/issues/2](url)
